version: '3'

services:
  currency-web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: 'currency-bot-web'
    restart: always
    ports:
      - "8081:80"
    volumes:
      - .:/app/
    links:
      - currency
    networks:
      - tier

  currency:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: 'currency-bot-php'
    restart: always
    volumes:
      - .:/app/
    networks:
      - tier

networks:
  tier:
    external:
      name: telegram-bots-network